const data = [
    {
        id: 1,
        title: 'VNGGames hợp tác với Webzen và Kingnet phát hành MU Lục Địa VNG tại Việt Nam',
        link: 'https://www.vng.com.vn/news/press-release/mu-luc-dia-vng.html',
        datetime: '07:00 AM | 30/03/2025',
        description: 'Hợp tác chiến lược giữa ba bên nhằm mang đến những tựa game chất lượng cao, tối ưu cho thị trường Việt Nam, khởi động với việc phát hành chính thức tựa game MU Online phiên bản di động với tên gọi MU Lục địa VNG trong tháng 4.2025.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/LG/GE25/MU%201.jpg', 
        proper_news: 'News/News_1/News_1.html',
        category:"press",
    },
    {
        id: 2,
        title: 'Thể thao điện tử lần đầu tiên được vinh danh tại chương trình "Vinh quang thể thao Việt Nam 2025"',
        link: 'https://www.vng.com.vn/news/press-release/vietnam-sports-glory-2025.html',
        datetime: '09:00 AM | 24/03/2025',
        description: 'Bộ môn Thể thao điện tử lần đầu được vinh danh tại chương trình “Vinh quang Thể thao Việt Nam 2025”.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/LG/GE25/1.jpg',
        proper_news: 'News/News_2/News_2.html',
        category:"press",
    },
    {
        id: 3,
        title: 'Zalopay ra mắt tính năng “Quét QR quốc tế” tại Singapore',
        link: 'https://www.vng.com.vn/news/enterprise/global-qr-scanning.html',
        datetime: '05:00 PM | 20/03/2025',
        description: 'Du khách Việt đến Singapore đã có thể sử dụng ứng dụng Zalopay để quét mã QR và thanh toán dễ dàng như người bản địa.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/LG/ZLP2025/CROSS-BORDER_2x1.jpg',
        proper_news: 'News/News_3/News_3.html',
        category:"business",
    },
    {
        id: 4,
        title: 'VNGGames ra mắt Level Up Launcher - nền tảng game PC đột phá cho trải nghiệm tối ưu',
        link: 'https://www.vng.com.vn/news/enterprise/level-up-launcher.html',
        datetime: '05:00 PM | 20/03/2025',
        description: 'VNGGames vừa chính thức giới thiệu Level Up Launcher - nền tảng tích hợp các tựa game PC, mang đến trải nghiệm game tiện lợi và toàn diện cho người dùng.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/LG/VNG2025/Levelup%20launcher.jpg',
        proper_news: 'News/News_4/News_4.html',
        category:"business",
    },
    {
        id: 5,
        title: 'VNGGames hợp tác chiến lược cùng VTVCab, thúc đẩy eSports Việt Nam phát triển',
        link: 'https://www.vng.com.vn/news/enterprise/vnggames-hop-tac-chien-luoc-cung-vtvcab-thuc-day-esports-viet-nam-phat-trien.html',
        datetime: '08:00 PM | 20/03/2025',
        description: 'Ngày 13/03/2025, VNGGames và Tổng Công ty Truyền hình Cáp Việt Nam (VTVCab) đã ký kết thỏa thuận hợp tác chiến lược, đánh dấu bước ngoặt trong việc kết hợp giữa ngành truyền hình và hệ sinh thái thể thao điện tử (eSports), mang đến trải nghiệm mới cho người hâm mộ tại Việt Nam.',
        image: '//corp.vcdn.vn/products/upload/vng/source/Products/Games/DSC08343.jpg',
        proper_news: 'News/News_5/News_5.html',
        category:"business",
    },
    {
        id: 6,
        title: 'Nhiều bệnh viện tuyến huyện tại Hà Nội chuyển đổi số hiệu quả nhờ Zalo',
        link: 'https://www.vng.com.vn/news/enterprise/zalo-mini-app-cds.html',
        datetime: '08:50 PM | 20/03/2025',
        description: 'Thực hiện chủ trương chuyển đổi số của Chính phủ và định hướng của Bộ Y tế (Quyết định 5316/QĐ-BYT), nhiều bệnh viện tại Hà Nội đã tiên phong đưa dịch vụ lên các nền tảng số.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/LG/Zalo2025/1.jpg',
        proper_news: 'News/News_6/News_6.html',
        category:"business",
    },
    {
        id: 7,
        title: 'VNGGames hợp tác cùng ON Live Esports, phát sóng các giải đấu eSports trên nền tảng VTVCab',
        link: 'https://www.vng.com.vn/news/enterprise/vnggames-hop-tac-on-live-esports-4328.html',
        datetime: '08:20 PM | 20/03/2025',
        description: 'ON Live Esports, đơn vị trực thuộc VTVCab sẽ là nhà tài trợ chính, đồng thời phối hợp cùng VNGGames tổ chức, sản xuất và phát sóng giải vô địch quốc gia Liên Minh Huyền Thoại  (VCS LMHT) với tên gọi chính thức ON Live Vietnam Championship Series 2025.',
        image: '//corp.vcdn.vn/products/upload/vng/source/SMT/ad-4nxcm0zrjopm87mut-nwpz4y6cwmumozqex1ldhc5yufef-k7i8hkfrpbmapx6nqdxjaezllnufmx6n6dk6zemjbh85lefdxpjbzm1wzkdskm-k4ecxz2vauuuswund0rvdbi8jnoba-31509370865752038776519.png',
        proper_news: 'News/News_7/News_7.html',
        category:"business",
    },
    {
        id: 8,
        title: '22 triệu người dùng trải nghiệm loạt tính năng đón Tết Ất Tỵ 2025 của Zalo',
        link: 'https://www.vng.com.vn/news/enterprise/zalo-don-tet-at-ty-2025.html',
        datetime: '11:20 PM | 20/03/2025',
        description: 'Trong dịp Tết Ất Tỵ 2025 vừa qua, Zalo tiếp tục chứng minh vị thế “ứng dụng quốc dân” khi loạt tính năng mới ra mắt bao gồm Sticker tràn màn hình, Thiệp AI, zStyle Lì xì, Hỏi đáp với AI đã thu hút hơn 22 triệu người dùng tham gia và trải nghiệm trong giai đoạn từ 27/01- 03/02/2025.',
        image: '//corp.vcdn.vn/products/upload/vng/source/SMT/e16e98e9-73b6-4475-b0f0-abf2a3de24d2.jpg',
        proper_news: 'News/News_8/News_8.html',
        category:"business",
    },
    {
        id: 9,
        title: 'Báo cáo kết quả hoạt động quý 4 năm 2024',
        link: 'https://www.vng.com.vn/news/vng-reports/vng-snapshot-q4-2024.html',
        datetime: '4:50 PM | 20/03/2025',
        description: 'VNG Snapshot Q4.2024 trình bày tóm lược các chỉ số tài chính và những thông tin doanh nghiệp xoay quanh hiệu quả hoạt động, chiến lược kinh doanh của VNG, các mảng sản phẩm tính đến ngày 31/12/2024.',
        image: '//corp.vcdn.vn/products/upload/vng/source/About%20VNG/VNG%20Snapshot/Thumbnail.png',
        proper_news: 'News/News_9/News_9.html',
        category:"report",
    },
    {
        id: 10,
        title: 'Thư từ nhiệm của thành viên BKS',
        link: 'https://www.vng.com.vn/news/shareholders/resignation-letter-of-member-of-the-bos.html',
        datetime: '5:20 PM | 22/03/2025',
        description: 'Ngày 13/03/2025, Hội Đồng Quản Trị (“HĐQT”) của Công Ty Cổ Phần VNG nhận được Đơn xin từ nhiệm chức vụ thành viên Ban Kiểm Soát của ông Phạm Văn Đô La vì lý do cá nhân, thời gian từ nhiệm từ ngày 12/03/2025.',
        image: '//corp.vcdn.vn/products/upload/vng/source/News/z3369137993132_6a506a166543015f4734bd156c62b698%20(2).jpg',
        proper_news: 'News/News_10/News_10.html',
        category:"shareholder",
    },
    {
        id: 11,
        title: 'VNG trở thành nơi làm việc tốt nhất Việt Nam 2023',
        link: 'https://vng.com.vn/news/enterprise/vng-kien-tri-thuc-hien-su-menh-tro-thanh-noi-lam-viec-tot-nhat.html',
        datetime: '5:20 PM | 22/03/2024',
        description: 'VNG tiếp tục được xếp hạng trong Top 5 doanh nghiệp lớn (trên 1000 nhân viên) có môi trường làm việc tốt nhất Việt Nam năm 2023.',
        image: 'https://corp.vcdn.vn/products/upload/vng/source/News/VNG%20daily%20news/VNG%20Great%20Place%20To%20Work.jpg',
        proper_news: 'News/News_11/News_11.html',
        category:"business",
    }
];
export default data